## Why Use Numpy?

* Provides an efficient storage.
* Provides better ways to handle data for processing.
* Uses less memory to store data.

## Importing

In [1]:
import numpy as np

## Creating Arrays

In [2]:
# 1-d array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2-d array
b = np.array([[9,8,7],[6,5,4]]) 
print(b)

[[9 8 7]
 [6 5 4]]


In [4]:
# 3-d array
c = np.array([[[9,8,7],[6,5,4]],[[3,2,1],[1,2,3]]])
print(c)

[[[9 8 7]
  [6 5 4]]

 [[3 2 1]
  [1 2 3]]]


In [5]:
# Another method
my_matrix = [[1,2,3],[3,2,1],[4,3,2,1]]

In [6]:
print(my_matrix)

[[1, 2, 3], [3, 2, 1], [4, 3, 2, 1]]


In [7]:
np.array(my_matrix)

array([list([1, 2, 3]), list([3, 2, 1]), list([4, 3, 2, 1])], dtype=object)

## Built-in Methods

### ndim
* Returns the dimension of an array

In [178]:
a = np.array([1,2,3])
b = np.array([[9,8,7],[6,5,4]])

In [182]:
a.ndim # means 1-d array

1

In [184]:
b.ndim # means 2-d array

2

### shape
* Returns the shape of an array

In [186]:
a.shape (rows,cols)

(3,)

In [188]:
b.shape (rows,cols)

(2, 3)

### arange
* Returns a range of numbers within a given interval.

In [8]:
np.arange(0,20) # proving a range (inclusive,exclusive).

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
np.arange(0,21,2) # Advancing it by providing a step value (steps up the range by 2).

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### itemsize
* Returns the size of the items in an array

In [190]:
a.itemsize

4

In [192]:
b.itemsize

4

### zeros & ones
* Creates an array of zeros and ones.

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((3,4)) # Giving it a proper shape.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,4)) # Giving it a proper shape.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.ones(3)*5 # Converting it to any number we want.

array([5., 5., 5.])

In [16]:
np.ones((3,4))*10 # one more example of it.

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

### linspace
* Returns evenly spaced numbers over a specified interval.

In [20]:
np.linspace(0,1) # Gave an evenly spaced numbers between 0 to 1.

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [32]:
np.linspace(0,1,5) # 5 here is the number of evenly spaced digits we want.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### eye 
* Creates an identity matrix. 
* Returns a 2-D array with 1's as the diagnol and 0's elsewhere.

In [42]:
np.eye(5) # You can see here a 2-d array with all the diagnols as 1's and 0's elsewhere.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
np.eye(4,3) # another example....

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

## Random

Numpy also has lots of ways to create random number arrays.

### rand
* random samples from a uniform distribution over [0,1] (Decimal numbers)

In [40]:
np.random.rand(3,3) # does not contain negative values.

array([[0.92546247, 0.36268203, 0.50506371],
       [0.36722542, 0.56388634, 0.19700815],
       [0.16282339, 0.69031089, 0.47917089]])

In [41]:
np.random.rand(4,3) # another eample...

array([[0.77071904, 0.66346409, 0.44386858],
       [0.84892981, 0.17505332, 0.2949054 ],
       [0.30825034, 0.93283465, 0.99965905],
       [0.31242204, 0.06794855, 0.53700552]])

### randn
* random samples from a standard normal distribution over [0,1] 

In [37]:
np.random.randn(3,3) #  # does contain negative values.

array([[-2.86166851,  0.65183598, -0.60873545],
       [ 2.097769  , -0.60518934,  0.47099481],
       [-2.13614874,  1.59244311, -1.69259983]])

In [39]:
np.random.randn(4,3) # One more example...

array([[ 6.59323761e-01,  2.68703031e-01,  5.37171097e-01],
       [ 1.66787000e+00,  1.06246580e+00, -1.02847483e+00],
       [ 2.13865420e+00,  1.15599087e-02, -1.59304428e-01],
       [-6.05459209e-01,  1.69375865e+00,  1.79166995e-03]])

### randint
* returns random 'integers' from low (inclusive) to high (exclusive).

In [34]:
np.random.randint(1,10,5) # 5 here is the no. of digits you want (as seen earlier aswell)

array([7, 2, 3, 8, 6])

In [36]:
np.random.randint(1,10,10) # another example...

array([8, 7, 6, 8, 2, 7, 1, 3, 7, 1])

## Array Attributes & Methods 

### reshape
* returns an array containing the same data with a new shape (provided).

In [61]:
arr = np.ones((4,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
arr.reshape(2,6) # reshaping the arr shape to (2,6) 

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### max, min, argmin, argmax

In [63]:
arr2 = np.array(np.random.randint(1,10,10))
arr2

array([3, 3, 9, 3, 8, 6, 9, 6, 3, 7])

In [70]:
arr2.max() # returns the maximum value 

9

In [69]:
arr2.min() # returns the minimum value

3

In [71]:
arr2.argmax() # returns the index number of the maximum value.

2

In [73]:
arr2.argmin() # returns the index number of the minimum value.

0

### shape 
* is an attribute an array has (not a method)
* returns the shape of an array

In [78]:
arr2.shape # (rows,cols)

(10,)

In [79]:
arr.shape # (rows,cols)

(4, 3)

### dtype
* you can grab the data-type of any array or an object.

In [80]:
arr.dtype

dtype('float64')

In [81]:
arr2.dtype

dtype('int32')

## Indexing & Selection (1-D array)
Using the index values to grab/select a specific number or a specific range of numbers.

In [83]:
arr[2] # mentioning the index no. under [], we want to grab

array([1., 1., 1.])

In [85]:
arr2[3] # another example...

3

In [88]:
arr2[0:3] # here I have given a range of index (inclusive:exclusive)

array([3, 3, 9])

## Broadcasting
Setting a value via index range.

In [89]:
arr2[0:3] = 100

In [91]:
arr2 # see what happened here? (we changed the value from index 0:3 to 100).

array([100, 100, 100,   3,   8,   6,   9,   6,   3,   7])

In [92]:
arr[0:2] = 100

In [93]:
arr # another example to make it clear.

array([[100., 100., 100.],
       [100., 100., 100.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

## Slicing
* Lets you slice through an array or an object and return a particular part of it.

In [98]:
arr

array([[100., 100., 100.],
       [100., 100., 100.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [96]:
# Slicing through (arr)
slice_of_arr = arr[0:2] # taking a particular part of it.

In [97]:
slice_of_arr # getting what we did here? 

array([[100., 100., 100.],
       [100., 100., 100.]])

In [99]:
# Now, advancing some stuff
slice_of_arr[:] = 99

In [101]:
slice_of_arr # We did broadcasting here (we have seen this earlier)

array([[99., 99., 99.],
       [99., 99., 99.]])

## Copy
* Let's you make a copy of an array or an object.

In [104]:
arr_copy = arr2.copy()

In [105]:
arr_copy

array([100, 100, 100,   3,   8,   6,   9,   6,   3,   7])

## Indexing a 2-D Array (Matrices)

In [108]:
arr_2d = np.array(([5,10,15],[20,15,30],[35,40,45]))

In [109]:
arr_2d

array([[ 5, 10, 15],
       [20, 15, 30],
       [35, 40, 45]])

In [110]:
# Indexing a row
arr_2d[1]

array([20, 15, 30])

In [121]:
# Getting an individual value
arr_2d[1][1] # [rows][cols]

15

In [122]:
# A better way to do it
arr_2d[1,1] # [rows,cols]

15

In [119]:
# 2-d array slicing
arr_2d[1:3,0:2] # giving it a range to get a specific part (We have used range before)

array([[20, 15],
       [35, 40]])

In [123]:
arr_2d[1,:] # Taking one more example...

array([20, 15, 30])

In [137]:
# Fancy indexing
arr_2d = np.zeros((4,4)) 

In [138]:
arr_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [139]:
# This is a bit advance (using for loop)
for i in range(len(arr)): # taking the length of the arr as a range i.e 4
    arr_2d[i] = i # replacing the arr_2d iteration by the iteration of arr (try it yourself to understand it)
arr_2d

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

## Selection 

In [140]:
arr = np.arange(1,11)

In [141]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [144]:
arr > 4 # Returns a boolean value

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [145]:
arr[arr>4] # use this to get the actual result

array([ 5,  6,  7,  8,  9, 10])

In [146]:
# Another longer way to do it
bool_arr = arr>4

In [148]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [151]:
arr[bool_arr] 

array([ 5,  6,  7,  8,  9, 10])

In [150]:
# Taking a diff example
x= 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Numpy Operations

### arithmetic

In [163]:
arr = np.arange(0,10)

In [164]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
arr + arr # addition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [166]:
arr - arr # substraction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [167]:
arr * arr # multiplication

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [168]:
arr / arr # divison (Notice: even if the answer is infinity it does return a value)

<ipython-input-168-7418df9d563a>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr # divison (Notice: even if the answer is infinity it does return a value)


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [169]:
arr**3 # power to 

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

### universal array functions

In [170]:
np.sqrt(arr) # square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [171]:
np.exp(arr) # exponential

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [172]:
np.sin(arr) # sin

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [173]:
np.log(arr) # log

<ipython-input-173-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Linear Algebra

In [200]:
a = np.ones((2,3))
b = np.ones((3,2))*2

In [204]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [205]:
b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [203]:
# a * b (won't work)

In [206]:
np.matmul(a,b) # (matmul) maths multiplication method

array([[6., 6.],
       [6., 6.]])

In [217]:
# Finding a determinant
c = np.identity(3) # identity is equal to eye

In [218]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [219]:
np.linalg.det(c) # applying linear algebra (linalg) & determinant (det)

1.0

## Vertically Stacking Vectors

In [231]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8]) 

In [233]:
v1

array([1, 2, 3, 4])

In [234]:
v2

array([5, 6, 7, 8])

In [223]:
np.vstack([v1,v2]) # vertically stacking both (v1,v2)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Horizontally Stacking Vectors

In [227]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

In [229]:
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [230]:
h2

array([[0., 0.],
       [0., 0.]])

In [226]:
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Thank you !